import Head from 'next/head'
import Terminal from '../components/Terminal'


export default function Home() {
  return (
    <div className=" h-screen flex items-center justify-center w-full bg-background bg-cover">
      <Head>
        <title>Create Nex App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" max-h-[70vh] rounded-xl bg-white bg-opacity-60 backdrop-filter backdrop-blur-lg flex flex-col h-[70vh] max-w-3xl font-bold">
      <div className=' pt-2 pb-2 pl-3 rounded-t-xl w-full bg-gray-700 bg-opacity-60 backdrop-filter backdrop-blur-lg h-6 flex items-center'>
        <div className=' bg-mxim mr-2 rounded-full w-4 h-4'></div>
        <div className=' bg-minm mr-2 rounded-full w-4 h-4'></div>
        <div className=' bg-clcs rounded-full w-4 h-4'></div>
      </div>
      <div className='pr-4 pl-4'>
        <h1>
          yajushvyas:$ <span className=" text-txtc">type help to start</span>
        </h1>
        <p>
          Visit{" "}
          <a href="https://discord.com/invite/bVxCeh9WDA" target="_blank" rel="noreferrer">
            my bababoi server
          </a>
        </p>
        <Terminal />
      </div>
      </main>
    </div>
  )
}
